spring:
  h2:
    console.enabled: true
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
auth:
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 86400000
logging:
  file:
    path: './logs/'