# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build and push Docker image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Debug
      run: echo 'Username is ${{vars.DOCKER_USERNAME}} and pass encripted is ${{secrets.DOCKER_TOKEN}}'
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{vars.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}

    - name: Build Docker Image
      run: docker build -t ${{ vars.DOCKER_REGISTRY }}/SpringBoot-GithubActions-CI-Example:latest
      
    - name: Docker Push
      run: docker push ${{ vars.DOCKER_REGISTRY }}/SpringBoot-GithubActions-CI-Example:latest
